name: flakytestnifi

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    
    - name: Build with maven
      uses: actions/cache@v2
       
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Git clone
      run: git clone https://github.com/apache/nifi

    - name: Move to the target folder
      run: cd nifi

    - name: Git checkout
      uses: actions/checkout@v2
      with:
       ref: 2bd752d868a8f3e36113b078bb576cf054e945e8

    - name: Compile the test
      if: github.ref !='nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers'
      run: mvn install -DskipTests -am -pl

    - name: Run the test without nondex
      run: mvn test -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNameAndUserIdentityCnAttribute

    - name: Run the test with nondex
      run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -DnondexRuns=10 -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNameAndUserIdentityCnAttribute
