name: Test nifi

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn --batch mode --update-snapshots package

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Git clone
      run: git clone https://github.com/apache/nifi

    - name: Move to the target folder
      run: cd nifi

    - name: Git checkout
      run: git checkout 2bd752d868a8f3e36113b078bb576cf054e945e8

    - name: Compile the test
      run: mvn install -DskipTests -am -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers

    - name: Run the test without nondex
      run: mvn test -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNameAndUserIdentityCnAttribute

    - name: Run the test with nondex
      run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl nifi-nar-bundles/nifi-ldap-iaa-providers-bundle/nifi-ldap-iaa-providers -DnondexRuns=10 -Dtest=org.apache.nifi.ldap.tenants.LdapUserGroupProviderTest#testSearchGroupsWithNameAndUserIdentityCnAttribute
